name: Node.js CI/CD with IAM Role

on:
 # push:
  #  branches:
   #   - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Fetch MongoDB URI from Secrets Manager
        id: fetch-secret
        run: |
          SECRET=$(aws secretsmanager get-secret-value --secret-id my-app/mongodb-uri --query SecretString --output text)
          echo "MONGODB_URI=$SECRET" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          MONGODB_URI: ${{ env.MONGODB_URI }}
        run: npm test

      - name: Build application
        run: npm run build

      - name: Deploy application (Optional)
        if: success()
        run: echo "Deploy step here (e.g., uploading to a server)"
